### ISSUE TITLE
Make content hashing / duplicate detection optional

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#1]
At the moment the block checks whether a video has been uploaded before. If that is the case the access policy for the video is changed.

This should be optional as having the same video in multiple series is a use case.

**Comment by tobiasreischmann** [comment]
Should this really be optional? And if so, who makes the decision? The administrator of the whole platform, the teacher when creating the block instance or the teacher when uploading a file.
If the access policies of a video are derived from the series they belong to and one series belongs to one course I think we should forbid existing uploads to be reused, except when the existing upload belongs to the same course (series). Or not?

**Comment by ebbertd** [comment]
Yes it should be optional in my opinion and the decision should be made by the admins upon configuring the block. This is needed in order to enable users to upload the same videos in multiple courses.

**Comment by tobiasreischmann** [comment]
I created a new setting in the blocks config. Is the setting doing what you intended (based on the description?) :)
![image](https://user-images.githubusercontent.com/9437254/32447811-64e0b370-c30d-11e7-8039-547d51173a30.png)

**Comment by ebbertd** [comment]
Yes

**Comment by tobiasreischmann** [comment]
Solved by #4
