### ISSUE TITLE
Upload filetype restriction not enforced

### ISSUE THREAD

**Issue by t-schroeder** [unirz-tu-ilmenau/moodle-block_opencast#105]
You can upload any type of file. When you upload for example a PDF as your presentation the workflow will fail and you can't remove the upload job again via the web interface. Moodle tries to upload the file and run the workflow every time the cron task is run. So you need to manually delete these upload jobs from the DB.

It's probably best to restrict the uploaded file type to videos.

**Comment by t-schroeder** [comment]
While testing my fix I noticed that .ogg video files weren't accepted anymore. That's because for moodle .ogg is an audio file extension. After renaming the file to .ogv I could upload it again.

So this would be one new problem that I didn't have before. But in my opinion it's better than to let people upload any type of file and them not being able to cancel/delete the failed upload jobs.

**Comment by tobiasreischmann** [comment]
I think it would be also very nice to have a config field in the block admin settings, which lets the admin enter a comma separated list of fileendings, which are allowed for uploading.
That would make things much easier, since the allowed filetypes might also be dependent on the workflow the particular admin is running, right?

**Comment by t-schroeder** [comment]
Good idea. I don't know what a good default would be. We could leave the config field blank by default and blank could mean we use Moodle's "video" file types as a fallback. What do you think?

**Comment by t-schroeder** [comment]
I added the config setting. I noticed when using the normal filepicker you can't specify arbitrary file extensions. You can only specify ones for which Moodle knows a file type (under Site administration -> Server -> File types). I should probably also validate the new config field when it is changed by an admin to make sure no invalid extensions are entered.

**Comment by t-schroeder** [comment]
I just saw #85 and took Alexander's advice to use Moodle's built-in "filetypes" form element for the new admin setting.
