### ISSUE TITLE
Not all strings are available in AMOS

### ISSUE THREAD

**Issue by abias** [unirz-tu-ilmenau/moodle-block_opencast#125]
As already discussed with @tobiasreischmann :

The plugin unfortunately uses concatenation in the language pack (see https://github.com/unirz-tu-ilmenau/moodle-block_opencast/blob/7c56409528518b0dfcb97a364540dae5d03d4663/lang/en/block_opencast.php#L270). This is discouraged by AMOS and prevents the language pack from being imported into AMOS.

As a result, currently not all strings from the language pack are available for translation in AMOS. Additionally, most probably only an outdated language pack version is available as subsequent plugin versions were not imported to AMOS.

This must be fixed in the plugin's language pack.

**Comment by tobiasreischmann** [comment]
I think this is fixed now, Alex.
