### ISSUE TITLE
INSERT INTO mdl_block_opencast_ltimodule produce a dmlwriteexception

### ISSUE THREAD

**Issue by moodlebeuth** [unirz-tu-ilmenau/moodle-block_opencast#141]
Hello Tobias, Hello Alex,

I tried to use the preconfigured LTI with the Custom parameter "tool=ltitools/series/index.html" eingetragen. If I try to create a series I will get the following error message:
...
Error writing to database

Weitere Informationen über diesen Fehler
Debug info: FEHLER: NULL-Wert in Spalte »cmid« verletzt
Not-Null-Constraint
DETAIL: Fehlgeschlagene Zeile enthält (7, 32, null).
INSERT INTO mdl_block_opencast_ltimodule (courseid,cmid) VALUES($1,$2)
RETURNING id
[array (
'courseid' => 32,
'cmid' => NULL,
)]
Error code: dmlwriteexception
Stack trace:

line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 259 of /lib/dml/pgsql_native_moodle_database.php: call to
moodle_database->query_end()
line 975 of /lib/dml/pgsql_native_moodle_database.php: call to
pgsql_native_moodle_database->query_end()
line 1023 of /lib/dml/pgsql_native_moodle_database.php: call to
pgsql_native_moodle_database->insert_record_raw()
line 200 of /blocks/opencast/classes/local/ltimodulemanager.php:
call to pgsql_native_moodle_database->insert_record()
line 84 of /blocks/opencast/addlti.php: call to
block_opencast\local\ltimodulemanager::create_module()

Output buffer:

style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>(
! ) Notice: Trying to get property 'coursemodule' of non-object
in /var/www/moodle/blocks/opencast/classes/local/ltimodulemanager.php on
line _199_ colspan='5'>Call Stack bgcolor='#eeeeec'>#Time align='left'
bgcolor='#eeeeec'>Memory bgcolor='#eeeeec'>Function
bgcolor='#eeeeec'>Location align='center'>10.0000 bgcolor='#eeeeec'
align='right'>424208{main}(
) bgcolor='#eeeeec'>.../addlti.php:0 bgcolor='#eeeeec' align='center'>2
align='center'>0.0844 align='right'>5921256
bgcolor='#eeeeec'>block_opencast\local\ltimodulemanager::create_module(
) bgcolor='#eeeeec'>.../addlti.php:84 ...

The series will be created irrespective of the issue.

You don't use sections in your moodle system? Or how do the function knows on which place the series will be created?

Thanks & Greetings,
Michael

**Comment by abias** [comment]
Hi Michael,

I am sorry to hear that you have problems with a feature which I contributed to this plugin. And I am sorry for delay to answer your post.

I am somehow struggling to understand and reproduce your problem here.
Would you be able to provide steps to reproduce for me, ideally based on a fresh Moodle installation?

Thanks,
Alex

**Comment by moodlebeuth** [comment]
Hi Alex,

sorry for not answering for such a long time. But with the block version v3.8-r2, which we are using right now I can't reproduce.
Thanks for your attention. 

Greetings,
Michael
