### ISSUE TITLE
[STUDIO] error 401 : Invalid signature for signature method HMAC-SHA1

### ISSUE THREAD

**Issue by nyok92** [unirz-tu-ilmenau/moodle-block_opencast#143]
Hi, 
i'am trying to get the recorder button work on my moodle site, but ecerytime i've got this error;
```
HTTP ERROR 401
Problem accessing /lti. Reason:
Invalid signature for signature method HMAC-SHA1
Powered by Jetty:// 9.4.12.v20180830
```

My LTI connection is working, I can see the welcome page and brose the series tools and see videos.
But when i put the custom paramater ( tool=ltitools/series/index.html?series=SERIESID ) on my LTI settings, i don't see any videos. 

Do you have any idea ?

Moodle 3.8.2 (Build: 20200309)
opencast block v3.8-r2
opencast tool v3.8-r1 2019112100

**Comment by aliyevTU** [comment]
We have the same issue (invalid signature) with our setup. We found the problem & solution and will submit a pull request.

**Comment by nyok92** [comment]
I resintalled opencast 8,5 and the updated moodle block. It works well.
Now i'm trying to figure how the lti configuration works with the acl ...
I'll close this issue.
Thnaks
