### ISSUE TITLE
Invalid signature for signature method HMAC-SHA1

### ISSUE THREAD

**Issue by aliyevTU** [unirz-tu-ilmenau/moodle-block_opencast#144]
Moodle version: 3.5.10+
Opencast version: 8.3

The most recent Opencast block plugin update for Moodle introduced a button called "Record Video" on course page, which through configured LTI credintials (block_opencast_additionalsettings) creates an LTI link to the Opencast Studio.
On our setup when this button is clicked and LTI link is followed, Opencast displays the following error:

HTTP ERROR 401
Problem accessing /lti. Reason:
    Invalid signature for signature method HMAC-SHA1

LTI connection & credentials independent of Opencast block plugin tested by creating an external tool and using those. This test was successful, and thus ruled out any problem with the LTI link between servers or incorrect credentials.

To debug the problem (LTI signature mismatch), we followed both Opencast Block's and Moodle external tool's LTI link signature creation in the source code:
Opencast Block uses the following to create LTI signature: moodle/lib/oauthlib.phpL149 sign()
External Tool uses the following to create LTI signature: moodle/mod/lti/locallib.php:L2357 lti_sign_parameters()

In our setup sign() function doesn't produce valid signature, but lti_sign_parameters() function does. LTI parameter signature method has been modified from sign() to lti_sign_parameters() on recordvideo.php file. Modification has been successfully tested, and its been confirmed that, the reason "Record Video" button doesn't work is because sign() function doesn't sign the LTI parameters correctly on our setup. It might be related to Moodle version.

Pull request will follow.

**Comment by tobiasreischmann** [comment]
That is very strange. Especially because the sign function has not changed from 3.5.10 to 3.9.0.|
In fact, this function changed last 10 years ago.
Could you check at your installation, what the sign function looks like and if there are any local changes to it?
