### ISSUE TITLE
Extend list of videos by planned videos

### ISSUE THREAD

**Issue by tobiasreischmann** [unirz-tu-ilmenau/moodle-block_opencast#16]
It would be nice, if the list of videos within the block would also display the list of planned but not yet recorded videos.

**Comment by TamaraGunkel** [comment]
Should the planned videos be displayed that have the same series ID?
If yes, these videos are already displayed in the table but they are not marked as planned.

**Comment by ebbertd** [comment]
Yes, planned videos with the same series id should be displayed with the status planned.

**Comment by tobiasreischmann** [comment]
The same series id than what?

**Comment by TamaraGunkel** [comment]
As the series id that is associated with the block instance
