### ISSUE TITLE
Configuration option for additional access policies

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#2]
In Opencast one might have configured groups of users which should have access to every recording / video in the system. Therefore it would be useful to be able to configure access policies which are added to every recording / video that is being uploaded via the Opencast block in Moodle.

**Comment by tobiasreischmann** [comment]
What do you mean with access policies "added" to every recording. Do you mean to ensure within moodle that only certain users can access the video? Or do you mean to define the access policies in moodle and then export them to opencast?

Moodle has two different concepts for access policies.
1. You can define capabilities. Users have (or have not) these based on their role in the current context (e.g. student in a course). These capabilities can then be used on code level to restrict the access to certain functionalities (e.g. viewing a video).
2. You can define accessibility settings for every single activity (e.g. a file). There you can define that only users which belong to a certain group can view this activity.
Which one do you think is more suitable for your purpose?

**Comment by ebbertd** [comment]
I mean added in Opencast. Independent of who can do what in Moodle I want to be able to add Opencast roles by default to the recordings. The goal is to ensure that admins can edit all videos in Opencast, for that use case I would have to add the role ROLE_ADMIN to every recording.

**Comment by tobiasreischmann** [comment]
Have you already tested the plugin in this regard? I think this role assignment is already done. However, it might be the case that it did not work prior to my latest changes. And in the current state the access rights are only set after the workflow is completed. Is this a problem?

**Comment by tobiasreischmann** [comment]
The following requirements were identified:
- Make group creation optional.
- Allow to specify the group name by the moodle admin using a pattern with placeholders like [COURSEID] [COURSENAME]
- Allow to specify the series name by the moodle admin using a pattern with placeholders like [COURSEID] [COURSENAME]
- Allow to add additional roles (ACL) to each upload, including custom actions.
- These roles might again use patterns with placeholders like [COURSEID]

**Comment by tobiasreischmann** [comment]
I created a milestone from this issue:
https://github.com/unirz-tu-ilmenau/moodle-block_opencast/milestone/1

**Comment by tobiasreischmann** [comment]
Split up to #5, #6, #7, #8
