### ISSUE TITLE
As an instructor I need to be able to manage student access to my uploaded videos

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#22]
As an instructor I need to be able to manage student access to my uploaded videos. It should be possible to remove student access to a video without deleting it and it should be possible to add these rights again later on.

**Comment by tobiasreischmann** [comment]
Could be solved using a visibility icon instead of the garbage bin behind each video entry. In the admin settings the ACL rules would need to extended with a flag, which tells if the ACL rules are removed for an "invisible" video.
