### ISSUE TITLE
Implement deleting videos in Opencast

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#24]
It should be possible for users to delete uploaded videos from Opencast. In Opencast this is a two part process. First the video has to be retracted from everything and only then it can be deleted.

**Comment by tobiasreischmann** [comment]
Connected to this is a current problem when hitting the delete button. Somehow the courseid is lost during the process and the error "Can not find data record in database table course" is thrown. Please, have a look at this problem, while working on this issue.

**Comment by tobiasreischmann** [comment]
Hey Andi,
will the improvements, you are talking about, be implemented for this block? And if so, will you contribute them here through a pull request?
I would be very interested in your removal of upload limits. According to my investigations this is not possible without moodle core changes (see #20).
Greetings,
Tobias

**Comment by synergy-wagner** [comment]
Hi Tobias, 

we have already developed a solution and some other changes, but the customer has not yet decided, how to contribute this to your repository. 

Your are right, would need a core change to limit the upload size to specific values, but it is possible to unlimit the upload size in total: 

Our solution:
- created a role with suitable capability and assign this role in context of the block.
- changed the page context of upload form page to the block context to make this work.

Kind regards
Andi

**Comment by synergy-wagner** [comment]
Deleting of videos is now possible for us, but Sven Stauber has to update the SWITCHCast server to SWITCHcast 5.0  make this work. So it may not work for lower versions of opencast.

**Comment by tobiasreischmann** [comment]
Fixed by the changes by synergy and #62.
