### ISSUE TITLE
Make publication channel column optional

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#25]
As an administrator I would like to be able to configure if the users see the column with the publication channels in the list of the published videos.

**Comment by TamaraGunkel** [comment]
What do you mean with users? Do you mean teachers or opencast administrators?

**Comment by ebbertd** [comment]
By users I mean all users who have access to the block within a course and are able to see the uploads / planned videos. So, that should be teachers as well as opencast administrators.

**Comment by tobiasreischmann** [comment]
Would you like to differentiate between the two groups? Or one setting to rule them all ;)

**Comment by ebbertd** [comment]
One setting to rule them all :D

On 18 June 2018 11:42:31 CEST, Tobias Reischmann <notifications@github.com> wrote:
>Would you like to differentiate between the two groups? Or one setting
>to rule them all ;)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unirz-tu-ilmenau/moodle-block_opencast/issues/25#issuecomment-397999576

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
