### ISSUE TITLE
When creating a series prefil the series name with the course name

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-block_opencast#47]
As an administrator it is possible to create a new series for a course. When doing so one is prompted to enter a series name. This should be pre filled with the course name.

**Comment by tobiasreischmann** [comment]
I would suggest, that this is prefilled with the Series name defined in the admin settings. (Which could be [COURSENAME])

**Comment by ebbertd** [comment]
That's the better idea.
