### ISSUE TITLE
Filter listed workflows in dropdown

### ISSUE THREAD

**Issue by mtneug** [unirz-tu-ilmenau/moodle-block_opencast#52]
Most workflows are just used for inclusions. These should not be used directly. Opencast has the notion of tags that determine in what situations running a particular workflow does make sense. [In 5.x these are](https://docs.opencast.org/develop/admin/configuration/workflow/):

- `upload`: Usable for uploaded media
- `schedule`: Usable for scheduled events
- `archive`: Usable for archived media
- `delete`: Usable for deletion of events with publications
- `editor`: Usable from the video editor

Before 5.x there was a `-ng` suffix for all but the last tag.

When querying `/workflow/definitions.json` the tag is represented as either:

```js
// no tags
{ "tags": "" }

// one tag
{
  "tags": {
    "tag": "archive-ng"
  }
}

// two or more tags
{
  "tags": {
    "tag": ["schedule-ng", "upload-ng"]
  }
}
```

I would suggest to at least filter out the no tags case.

**Comment by tobiasreischmann** [comment]
If there are specific tags, which suite the two workflow settings fields, just tell me and I will reduce the set of workflows to these.

**Comment by ebbertd** [comment]
For the ACL update workflow the only tag possible is `archive` and for the upload workflow the only tag possible is `upload`. If a workflow is started when deleting an episode the workflow tag is `delete`.
