### ISSUE TITLE
Edit event metadata during and / or after upload

### ISSUE THREAD

**Issue by abias** [unirz-tu-ilmenau/moodle-block_opencast#83]
Currently, the metadata for an event which is uploaded to Opencast with block_opencast is only generated automatically from the video filename as far as I see. And we all know the users / teachers who label their files just with non-speaking filenames or with some strange complex scheme which only they understand.

I would like to propose to add functionality...
* ... which lets users set at least the title of the event manually. Don't rely on the fact that users know how to rename files in the Moodle filepicker. Show them a mandatory input field for the title of the uploaded videos instead.
* ... which lets users change the event metadata after the video has been uploaded and processed if needed
* ... which lets Moodle download the whole metadata catalog of Opencast and provide optional input fields for all metadata fields so that the whole catalog can be filled from within Moodle.

**Comment by t-schroeder** [comment]
This has since been implemented. Can the issue be closed then?

**Comment by abias** [comment]
Yes, the solution which has been implemented in the meantime is what I was looking for back then. Thanks to everyone who participated in this contribution!
