### ISSUE TITLE
Add a setting to restrict the uploadable video types

### ISSUE THREAD

**Issue by abias** [unirz-tu-ilmenau/moodle-block_opencast#85]
In https://github.com/unirz-tu-ilmenau/moodle-block_opencast/blob/master/classes/local/addvideo_form.php#L41, the block accepts the filetype group "video" for uploading. Looking at https://github.com/moodle/moodle/blob/master/lib/classes/filetypes.php, this group resolves to many filetypes and many of them might not be suitable or desired for uploading to Opencast.

Changing the video group to web_video would be an improvement, but you would still allow types like flv or swf which you most probably don't want to process in Opencast.

That's why I would propose to add an admin setting to the block to let the admin set a list of mimetypes which he want to allow for uploading. This can be realized with the Moodle mimetype chooser which is already used for example in mod_assign.

**Comment by t-schroeder** [comment]
Hi Alexander, I just noticed this issue after having implemented such a setting. Thanks for pointing out that the "filetypes" form field exists. I changed my solution from a normal text area with a custom validator to the suggested field type.

**Comment by abias** [comment]
Thanks, Tim.
As this feature is available in master, this issue can then be closed.
